name: common_sdk
description: Common funcs, widgets and utils for Flutter apps and packages development.
homepage: https://bloclibrary.dev/#/?id=sponsors
version: 0.1.0+8
# publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: '>=3.3.7'

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress: ^1.1.3
  intl: ">=0.17.0 <0.19.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
